---
config:
  themeVariables:
    xyChart:
      plotColorPalette: "#1F5FAD"
      backgroundColor: "#FFFFFF"
---
xychart-beta
    x-axis "Message size (bytes)" ["64", "256", "1K", "4K", "16K", "64K", "256K", "1M"]
    y-axis "BW average (Gb/s)" 0 --> 3.5
    line [0.05, 0.2, 0.7, 1.6, 2.3, 2.6, 2.7, 2.7]